### ISSUE TITLE
Serial with characters

### ISSUE THREAD

**Issue by kblumenau** [raschy/ioBroker.deyeidc#103]
I have two deye inverters up and running with v0.0.14 in iobroker. 

I now got a new one (M80G4) that has a serial number including a character at the end - this one is not accepted by the deyeidc adapter
other than that, the inverter looks the same compared to the other two

can this be adapted / will that one work?

thanks for your work and support!

**Comment by raschy** [comment]
I have always assumed that serial numbers are actually numbers. Which symbol is on the back of your M80G4?

**Comment by kblumenau** [comment]
Thanks for your quick answer!

What symbol do you mean? we can share more details through private msg if you want...
Serial printed on the back is a 9 digit number plus an F at the end
inverter is online and connected to the cloud, I added  it to the SolarPV config, serial was accepted but I do not see data yet (not connected). I also tried some of the other numbers I could find without success. 
As said, the other two old inverters work (local and cloud), so I thought I knew what I should do... but...

**Comment by raschy** [comment]
That was the question about the ‘F’. However, we can also exchange details by e-mail (also in German).

**Comment by kblumenau** [comment]
blume@gmx.li

**Comment by kblumenau** [comment]
SORRY! 
it was just my fault, using the wrong number. Using the correct number ("device serial number" on web interface) the adapter works perfectly, just as is did before. Thanks again for the work and support ... and sorry
