### ISSUE TITLE
DynDNS IP not possibe

### ISSUE THREAD

**Issue by radebold** [raschy/ioBroker.deyeidc#109]
Hi,

it is not possible to use dyndns?
IP address [#####.ddns.net] is not valid !

it is possible to add this support?

Thx.
Thomas

**Comment by raschy** [comment]
Hi Thomas, what is the use case for this extension? I have installed this, please install from Github, test and give feedback.

**Comment by radebold** [comment]
Hi rasche

I extended the IP Check, so it is also possible to put in a dyndns address
like xyz.dyndns.org

Thx

raschy ***@***.***> schrieb am Do. 11. Juli 2024 um 09:30:

**Comment by raschy** [comment]
Yes, I already understood the use. What is it used for/when? And, do you need any further forwarding? 
It's probably not enough if the public IP is recognized.

**Comment by radebold** [comment]
My use case I montitoring the inverter of my mum remotely with my Iobroker

raschy ***@***.***> schrieb am Do. 11. Juli 2024 um 14:34:

**Comment by raschy** [comment]
Should be fixed with version 0.0.15 (and later).
