### ISSUE TITLE
Sporadisch error im log

### ISSUE THREAD

**Issue by unstressable** [raschy/ioBroker.deyeidc#112]
Jemand eine Idee was das hier sein könnte:
<html>
<body>

deyeidc.2 | 2024-07-26 20:05:51.958 | error | Error: Frame CheckSum faulty! 58\|d \| Error: Frame CheckSum faulty! 58\|d at idcCore.checkDataFrame (/opt/iobroker/node_modules/iobroker.deyeidc/lib/idc-core.js:70:10) at Deyeidc.onData (/opt/iobroker/node_modules/iobroker.deyeidc/main.js:170:24) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.deyeidc/main.js:158:10) at Socket.emit (node:events:517:28) at addChunk (node:internal/streams/readable:368:12) at readableAddChunk (node:internal/streams/readable:341:9) at Readable.push (node:internal/streams/readable:278:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
-- | -- | -- | --

</body>
</html>

Hab das bei all meinen 4 Instanzen immer mal wieder.

**Comment by raschy** [comment]
Sollte mit der 0.1.0 gefixt sein.
