### ISSUE TITLE
Verbindungsfehler

### ISSUE THREAD

**Issue by sonny1985** [raschy/ioBroker.deyeidc#120]
Hallo.

Ich bleib derweil bei 0.0.14 (welche einwandfrei funktioniert) . Mit der 0.0.15er bekam ich tonnenweise irgendwelche Verbindungsfehler , rot markiert, ins Log. Mit der 0.0.16er waren sie immer noch da, allerdings wesentlich weniger (EHOST_unreach).
Fehler scheinen Netzwerkbezogen zu sein. (Ich erreich die Wechselrichter aber ohne Probleme an deren Weboberfläche)

**Edit: Hab eben das ganze Netzwerk bei mir neu gestartet (Um da irgendwelche Probleme ausschliessen zu können) und die 0.0.16 installiert
Falls der Fehler wieder auftritt: reiche dann einen Screenshot aus dem Log nach :)**

Falls er nicht wieder auftritt, lag es wohl an mir . Bisschen Geduld bitte.
Verwende Admin: 7.0.22, und JS controller: 6.0.9, NodeJS: 20.16.0
Danke und LG

**Comment by sonny1985** [comment]
![Screenshot 2024-08-03 092007](https://github.com/user-attachments/assets/46b1b503-9a8b-4a20-bf71-b219436903f2)

OK Ich bins nicht. :) 
In der instanzenansicht wird der betroffene WR dann "orange"- Starte ich die Instanz neu, ist er gleich wieder grün. Ein Update macht er alle 310 sekunden...
Ich hab 2 Instanzen am laufen.

**Comment by raschy** [comment]
Produzieren die WR ins Netz? Wenn nicht, kann keine Verbindung zum WR aufgebaut werden und die Instanz bleibt gelb.

**Comment by sonny1985** [comment]
Hi.
Klar sind beide Aktiv AC Seitig.
Mach ich , ich schalt ihn auf Debug, und schick in ner halben Stunde nen Screenshot nach :)

**Comment by raschy** [comment]
Ich weiß jetzt nicht, welchen WR du hast. Es gibt ein Verbindungstimeout von 10 Sekunden, welches die Verbindung nach dem Abholen - da nicht mehr gebraucht - schließt. Sollte das ein Problem werden, lass ich die Verbindung in der nächsten Version halt auf. Bitte Beobachten und berichten.

**Comment by sonny1985** [comment]
Ich hab einen Sun-300 und einen Sun-1600 in Verwendung.

Ich beobachte das einfach ein wenig, ich halt dich am laufenden, es kann allerdings durchaus sein, das es an meinem Netzwerk lag. (wer weiß). 
War das mit der Verbindung in der Version 0.0.14 gleich ? (Die hat nie irgendwelche Roten Fehlereinträge verursacht)
Die 0.0.15 war mit roten Fehlern am schlimmsten.

**Comment by raschy** [comment]
Ja, die 0.015 war etwas buggy. Da hatte ich zuviel wegoptimiert. 
Haben deine beiden SUN auch soetwas wie eine externe Relaisbox?

**Comment by sonny1985** [comment]
Nein, die relais hab ich nicht installiert 😊.  Mit denen geht generell garnixmehr.

**Comment by raschy** [comment]
Ich habe damals den Adapter so angepasst, dass die Kommunikation mit der Relaisbox rausgefiltert wird. Aber lass so wie es ist, generell eine Fehlerquelle weniger. Jetzt müssen wir nur noch schauen was orange/rot macht. Einfach wieder melden, Danke.

**Comment by sonny1985** [comment]
![Screenshot 2024-08-03 152641](https://github.com/user-attachments/assets/00ce18fb-bc3a-44fe-b16a-dbf212d4e95c)
![Screenshot 2024-08-03 152704](https://github.com/user-attachments/assets/00c52e31-5e9a-458b-83c7-e62c028cb3a0)

Ok, an mir liegts nicht :) 
LG

**Comment by sonny1985** [comment]
![Screenshot 2024-08-03 153144](https://github.com/user-attachments/assets/fae7a529-11f9-4e7c-acbb-9d09d133bcee)


Das hier ist mir noch aufgefallen wenn ich zwischen verschiedenen Adapterversionen (0.0.14 und 0.0.16) wechsle.

**Comment by raschy** [comment]
Versuch mal (morgen) direkt von Github zu installieren,

**Comment by sonny1985** [comment]
Guten morgen. Habs mal direkt von hier installiert. 
Hab gesehen, du hast das Timeout auskommentiert, und die Verbindung nun immer stehen lassen oder ?

Ich meld mich am Abend, wenn beide WR vom Netz getrennt und offline sind, nochmals ob es Fehlereinträge im Log gibt :) Bis jetzt sieht das prima aus !.
LG und schönen Sonntag.

**Comment by sonny1985** [comment]
Soo.

Das Log meldet mir am Tag bei beiden Instanzen , 4 Unterbrechungen. 
Wobei die Daten allerdings Lückenlos sind, seh ich in der Datenbank :)

Wenn das nun das gleiche ist vom Verbinden her wie die 0.0.14, versteh ich nicht, warum die 0.0.14 niemals einen einzigen Verbindungsfehler ins Log geschrieben hat .

Für mich ists nicht nachvollziehbar .
LG derweil

**Comment by raschy** [comment]
Bei mir läuft die 0.0.16 auch gegen zwei WR. Auf beiden Systemen habe ich keine einzige (unerwartete) Unterbrechung. Jetzt wird es für mich schwierig.

**Comment by sonny1985** [comment]
Eigenartig ist das wirklich, ich versteh es auch nicht.
Ich lass die 0.0.16 (Die Github version von hier) einfach mal drauf, und beobacht das einfach weiter.

**Comment by raschy** [comment]
Ja, mach das so. Beobachte weiter und berichte, sobald du erkennen kannst, wann das genau passiert. Vllt. kann ich dann noch etwas verbessern.

**Comment by sonny1985** [comment]
So , hatte die letzten 2 Tage keine roten Fehlermeldungen mehr im Log drin :)
Ich denk das kann man hier schließen. Bitte Frag mich nicht ob nun das aufrechterhalten der Verbindung dafür verantwortlich ist, oder da etwas anderes am werkeln war was für Probleme gesorgt hatte.

Hab auch bereits die 0.1.0er drauf :)

LG und dank.
