### ISSUE TITLE
Installation Fehler

### ISSUE THREAD

**Issue by Pocky2507** [raschy/ioBroker.deyeidc#23]
Node 8.16.1
NPM: 9.5.1

Bekomme beim installieren diese Fehlermeldung:

`$ iobroker url https://github.com/raschy/ioBroker.deyeidc --host rockpro64 --debug

Installing raschy/ioBroker.deyeidc#1c042ce4617e44dfb6fcb2a5bf37ab2dc37e2906... (System call)

npm WARN skipping integrity check for git dependency ssh://git@github.com/raschy/ioBroker.deyeidc.git

npm ERR! code 1

npm ERR! gyp info using node-gyp@7.1.2

npm ERR! gyp info using node@18.16.1 | linux | arm64npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"npm ERR! (node:17150) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)npm ERR! gyp info spawn /usr/bin/python3npm ERR! gyp info spawn args [npm ERR! gyp info spawn args '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',npm ERR! gyp info spawn args 'binding.gyp',npm ERR! gyp info spawn args '-f',npm ERR! gyp info spawn args 'make',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/bufferutil/build/config.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/node-gyp/addon.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/home/iobroker/.cache/node-gyp/18.16.1/include/node/common.gypi',npm ERR! gyp info spawn args '-Dlibrary=shared_library',npm ERR! gyp info spawn args '-Dvisibility=default',npm ERR! gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.16.1',npm ERR! gyp info spawn args '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',npm ERR! gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/bufferutil',npm ERR! gyp info spawn args '-Dnode_engine=v8',npm ERR! gyp info spawn args '--depth=.',npm ERR! gyp info spawn args '--no-parallel',npm ERR! gyp info spawn args '--generator-output',npm ERR! gyp info spawn args 'build',npm ERR! gyp info spawn args '-Goutput_dir=.'npm ERR! gyp info spawn args ]npm ERR! gyp info spawn makenpm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]npm ERR! make: cc: Command not foundnpm ERR! make: *** [bufferutil.target.mk:111: Release/obj.target/bufferutil/src/bufferutil.o] Error 127npm ERR! gyp ERR! build error npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2npm ERR! gyp ERR! stack at ChildProcess.onExit (/opt/iobroker/node_modules/node-gyp/lib/build.js:194:23)npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28)npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:291:12)npm ERR! gyp ERR! System Linux 5.15.93-rockchip64npm ERR! gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/bufferutilnpm ERR! gyp ERR! node -v v18.16.1npm ERR! gyp ERR! node-gyp -v v7.1.2npm ERR! gyp ERR! not oknpm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-06-23T07_01_45_324Z-debug-0.log

npm WARN skipping integrity check for git dependency ssh://git@github.com/raschy/ioBroker.deyeidc.git npm ERR! code 1npm ERR! path /opt/iobroker/node_modules/bufferutilnpm ERR! command failednpm ERR! command sh -c node-gyp-buildnpm ERR! make: Entering directory '/opt/iobroker/node_modules/bufferutil/build'npm ERR! CC(target) Release/obj.target/bufferutil/src/bufferutil.onpm ERR! make: Leaving directory '/opt/iobroker/node_modules/bufferutil/build'npm ERR! gyp info it worked if it ends with oknpm ERR! gyp info using node-gyp@7.1.2npm ERR! gyp info using node@18.16.1 | linux | arm64npm ERR! gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"npm ERR! (node:17150) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)npm ERR! gyp info spawn /usr/bin/python3npm ERR! gyp info spawn args [npm ERR! gyp info spawn args '/opt/iobroker/node_modules/node-gyp/gyp/gyp_main.py',npm ERR! gyp info spawn args 'binding.gyp',npm ERR! gyp info spawn args '-f',npm ERR! gyp info spawn args 'make',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/bufferutil/build/config.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/node-gyp/addon.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/home/iobroker/.cache/node-gyp/18.16.1/include/node/common.gypi',npm ERR! gyp info spawn args '-Dlibrary=shared_library',npm ERR! gyp info spawn args '-Dvisibility=default',npm ERR! gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/18.16.1',npm ERR! gyp info spawn args '-Dnode_gyp_dir=/opt/iobroker/node_modules/node-gyp',npm ERR! gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/bufferutil',npm ERR! gyp info spawn args '-Dnode_engine=v8',npm ERR! gyp info spawn args '--depth=.',npm ERR! gyp info spawn args '--no-parallel',npm ERR! gyp info spawn args '--generator-output',npm ERR! gyp info spawn args 'build',npm ERR! gyp info spawn args '-Goutput_dir=.'npm ERR! gyp info spawn args ]npm ERR! gyp info spawn makenpm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]npm ERR! make: cc: Command not foundnpm ERR! make: *** [bufferutil.target.mk:111: Release/obj.target/bufferutil/src/bufferutil.o] Error 127npm ERR! gyp ERR! build error npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2npm ERR! gyp ERR! stack at ChildProcess.onExit (/opt/iobroker/node_modules/node-gyp/lib/build.js:194:23)npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28)npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:291:12)npm ERR! gyp ERR! System Linux 5.15.93-rockchip64npm ERR! gyp ERR! command "/usr/bin/node" "/opt/iobroker/node_modules/.bin/node-gyp" "rebuild"npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/bufferutilnpm ERR! gyp ERR! node -v v18.16.1npm ERR! gyp ERR! node-gyp -v v7.1.2npm ERR! gyp ERR! not oknpm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-06-23T07_01_45_324Z-debug-0.log

host.rockpro64 Cannot install raschy/ioBroker.deyeidc#1c042ce4617e44dfb6fcb2a5bf37ab2dc37e2906: 1

ERROR: Process exited with code 25`

**Comment by raschy** [comment]
This does not seem to be a specific error of the adapter. Search the forum for "error 25". Possibly also a temporary problem with npm.

$ iobroker url https://github.com/raschy/ioBroker.deyeidc --host CT113 --debug
install raschy/ioBroker.deyeidc#1c042ce4617e44dfb6fcb2a5bf37ab2dc37e2906
NPM version: 9.5.1Installing raschy/ioBroker.deyeidc#1c042ce4617e44dfb6fcb2a5bf37ab2dc37e2906... (System call)
npm WARN skipping integrity check for git dependency ssh://git@github.com/raschy/ioBroker.deyeidc.git
npm ERR! code ERR_SOCKET_TIMEOUTnpm ERR! network Socket timeoutnpm ERR! network This is a problem related to network connectivity.npm ERR! network In most cases you are behind a proxy or have bad network settings.npm ERR! network npm ERR! network If you are behind a proxy, please make sure that thenpm ERR! network 'proxy' config is set properly. See: 'npm help config'npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-06-23T07_27_02_856Z-debug-0.log
upload [12] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/deyeidc.png deyeidc.png image/png
upload [11] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [9] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [8] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [7] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [6] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [5] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/pl/translations.json i18n/pl/translations.json application/json
upload [4] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [3] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [2] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/uk/translations.json i18n/uk/translations.json application/json
upload [1] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json
upload [0] deyeidc.admin /opt/iobroker/node_modules/iobroker.deyeidc/admin/jsonConfig.json jsonConfig.json application/json

Process exited with code 0
