### ISSUE TITLE
Reimport von JSON funktioniert nicht für Berechnete Werte

### ISSUE THREAD

**Issue by Reddingo** [raschy/ioBroker.deyeidc#37]
Ich musste den Adapter neu installieren da das Updfate von 0.0.4 auf 0.0.9 nicht geklappt hat.
Ich habe vorher die Settings per JSON exportiert. 

Nach dem Reimport waren alle Werte wieder da bis auf die "Werte (Formeln)" für die 2 Berechnung von DP1 bzw DP2 bei mir (Key, Name, Einheit und Faktor waren korrekt importiert)

Auch hat er nun für die brechneten Werte einen Faktor 2 gehabt, welche den Wert ja um 100 verkleinert? Das war vorher auch anders, aber gut möglich dass das bei Version 0.0.4 noch anders war

**Comment by raschy** [comment]
Das ist auch zu erklären. In der vorigen Version gab es zwei Felder für die zu brechneneden Werte. Ab der Version 0.0.5 gibt es nur ein Feld "Wert**e**(Formeln)". Daher kann der Import der JSON aus der Version 0.0.4 nicht funktionieren. Daher bitte diesen Tab komplett neu ausfüllen (Ist ja hoffentlich nicht soviel).

**Comment by Reddingo** [comment]
Okay. Das erklärt es. Waren zum Glück nur die 2 Power Berechnungen.

Und ich hab mich echt gefreut, dass du den Export und Reimport implementiert hattest, davor hat es mir echt gegraut die ganzen Werte neu einzugeben :-O

**Comment by raschy** [comment]
Ja gerne (ist aber bei den Adptern quasi im Standard schon drin). 
Da du den Sun600 hast, könntest du auch die Beispiel-JSON aus dem Repository (https://github.com/raschy/ioBroker.deyeidc/blob/main/deyeidc.MI600.json) nutzen. 
Dann musst du nur noch IP und Logger-SN eingeben.

**Comment by Reddingo** [comment]
Fürs nächste mal weis ich bescheid, vielen Dank

Hast du eigentlich eine digitale Kaffeekasse?

**Comment by raschy** [comment]
Nee lass mal. Ich mach das hier als Hobby - wenn ich helfen kan, gerne. Bis zum nächsten Bug

**Comment by Reddingo** [comment]
Okay. Wie du magst :-) 
bis jetzt lief es ja stabil
