### ISSUE TITLE
Adapter Objects didnt get autocreated

### ISSUE THREAD

**Issue by raidsec** [raschy/ioBroker.deyeidc#55]
Hello,

i created the required register and config entries for my deye inverter:

![image](https://github.com/raschy/ioBroker.deyeidc/assets/33294982/e1d68cee-fbb6-425b-b19b-171fee66c599)

![image](https://github.com/raschy/ioBroker.deyeidc/assets/33294982/a16158c1-a2f7-4776-af96-7cbdc157cf0f)

But after multiple restarts the Adapter Objects are not getting autocreated. Is this normal?

![image](https://github.com/raschy/ioBroker.deyeidc/assets/33294982/c0866d2d-5f75-404d-92b4-42bd88d34091)

![image](https://github.com/raschy/ioBroker.deyeidc/assets/33294982/41b8c7f8-e2d7-4e6c-9252-51818f2f6c8b)

Do i need to create the entries manually?

Node.js: v18.17.1
NPM: 9.6.7
deyeidc.0: v0.0.13

**Comment by raschy** [comment]
No, the individual data points are created by the adapter. It may help to stop and restart the adapter.

**Comment by raidsec** [comment]
Sure, have done a restart it multiple times. Also already reinstalled the adpter.
 Objects still did not get created.

**Comment by raschy** [comment]
I just reinstalled the adapter again. Here it has created all data points. Maybe it helps to stop the Adpter, delete the data tree 'deyeidc.0' and then start it again.

**Comment by raschy** [comment]
Node.js and npm are up to date and ok. Have you deleted the object tree?

**Comment by raidsec** [comment]
I created a new IOBroker Installation and tried your adapter again. It is working so it looks like a problem with my local installation. Your Adapter is fine. Thank you for your work.
