### ISSUE TITLE
RangeError im Log

### ISSUE THREAD

**Issue by dontobi** [raschy/ioBroker.deyeidc#56]
**Describe the bug**  
Ich nutze die aktuellste Version und erhalte den folgenden Eintrag im ioBroker Log:
```RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 10. Received 13```
Ich nutze einen Deye SUN10K.

**To Reproduce** 
1. Öffne das ioBroker Log

**Expected behavior**  
Keine Meldung im Log.

**Screenshots & Logfiles**  
Kann ich nachliefern, wenn dieser benötigt wird.

**Versions:**  
 - Adapter version: 0.0.13
 - JS-Controller version: 7.1.5
 - Node version: 18.18.1
 - Operating system: Docker Container 9.0.1

**Additional context**  
Nichts.

**Comment by raschy** [comment]
Please try Version 0.0.14 and talk about it.

**Comment by dontobi** [comment]
Die Error Meldung ist seit dem Update nicht mehr aufgetreten.
