### ISSUE TITLE
How to write register: 40 Active Power Regulation?

### ISSUE THREAD

**Issue by fat-randy** [raschy/ioBroker.deyeidc#88]
Hallo Raschy,

ich lese mit deinem Adapter erfolgreich zwei Deye Sun 600 Mikrowechselrichter aus. Funktioniert super.
Da meine WR über keine Modbus Schnittstelle verfügen würde ich auch gerne das Register: 40 Active Power Regulation damit beschreiben um eine Nulleinspeisung zu erreichen.
Leider speichert er den Wert nicht. Ich vermute ich beschreibe damit nur den Logger und der holt sich den Wert immer wieder neu vom Wechselrichter.
Gibt es da irgendeine Möglichkeit das mit deinem Adapter zu machen? Oder mit Modbus Adapter im iOBroker.
Die Lösung von: https://github.com/kbialek/deye-inverter-mqtt?tab=readme-ov-file#readme ist mir zu kompliziert.
Bitte um Antwort.
Gruß Manuel

**Comment by raschy** [comment]
Hallo Manuel, Kannst du mir bitte mal schildern, was du bisher gemacht bzw. versucht hast. Gerne auch per Mail an raschy@gmx.de. Möglicherweise habe ich eine Lösung für dich.

**Comment by JoGu01** [comment]
Hi ihr beiden. Mag mir noch einer sagen wie ihr das gelöst habt?

**Comment by raschy** [comment]
Mach mal den gleichen Weg wie fat-randy, per Mail.
