### ISSUE TITLE
Iobroker DEYE 12K LAN Adapter

### ISSUE THREAD

**Issue by Photographix** [raschy/ioBroker.deyeidc#94]
**Describe the bug**  
Adapter liest im IObroker keine Werte aus

**To Reproduce**  
- Deye 12k-SG04LP3-EU -> **LAN** Adapter
- IObroker
- Adapter deyeidc v0.0.14
- json File from github (deyeidc.Sun12KP3.json)
- Settings wie IP, Pollimg und Port gesetzt

**Expected behavior**  
Der Adapter liest nach "Objekte" alle Werte vom Deye aus

**Screenshots & Logfiles**  
Fehler bei Protokolle Adapter deyeidc:
`Error: Frame CheckSum faulty! 8a|2a | Error: Frame CheckSum faulty! 8a|2a at idcCore.checkDataFrame (/opt/iobroker/node_modules/iobroker.deyeidc/lib/idc-core.js:70:10) at Deyeidc.onData (/opt/iobroker/node_modules/iobroker.deyeidc/main.js:170:24) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.deyeidc/main.js:158:10) at Socket.emit (node:events:517:28) at addChunk (node:internal/streams/readable:368:12) at readableAddChunk (node:internal/streams/readable:341:9) at Readable.push (node:internal/streams/readable:278:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Versions:**  
 - Adapter version: 0.0.14
- Plattform: docker (official image - v9.1.1)
- RAM: 15.3 GB
- Node.js: v18.19.1(18.20.0)
- NPM: 10.2.4(10.5.0)

**Comment by raschy** [comment]
Ich vermute mal, dass es irgendein Firmware-Update gibt, mit dem die Checksumme nun anders berechnet wird. Wäre es ein genereller Fehler hätte sich schon mehr Nutzer melden müssen. Als erste Möglichkeit bitte mal den Adapter direkt von Github installieren.

**Comment by Rene55-0** [comment]
Ist ein ganz anderes Fehlerbild. Ein anderer Nutzer hat dieses (mit beiden Fehlern) auch so erlebt. Er wartet gerade auf einen neuen WR, danach sehen wir ob es am Adapter (insbesondere bei den Großen) liegt oder sonstwo. Im Augenblick bin ich ratlos.

**Comment by raschy** [comment]
Ist ein ganz anderes Fehlerbild. Ein anderer Nutzer hat dieses (mit beiden Fehlern) auch so erlebt. Er wartet gerade auf einen neuen WR, danach sehen wir ob es am Adapter (insbesondere bei den Großen) liegt oder sonstwo. Im Augenblick bin ich ratlos.

**Comment by raschy** [comment]
No new findings. Therefore closed from my side.
